/**
 * @file TsInjectablePlugin
 * @author Jim Bulkowski <jim.b@paperelectron.com>
 * @project @framework
 * @license MIT {@link http://opensource.org/licenses/MIT}
 */

export const template = `// Generated by the Pomegranate cli on {{creationDate}}

import {CreatePlugin} from 'pomegranate'

const MyPlugin = CreatePlugin('anything')
  .configuration({
    name: 'example',
    injectableParam: 'example',
    depends: [],
    provides: [],
    optional: []
  })
  .variables({})
  .hooks({
    load: () => {
      return {}
    },
    start: () => {
      
    },
    stop: () => {
      
    }
  })
  .directories([])
  .commands(() => {
    
  })
  .installs([])

export const Plugin = CreatePlugin('application')
  .configuration({
    name: '{{name}}',
  })
  .applicationPlugins([
    MyPlugin
  ])
`