/**
 * @file TsInjectablePlugin
 * @author Jim Bulkowski <jim.b@paperelectron.com>
 * @project @framework
 * @license MIT {@link http://opensource.org/licenses/MIT}
 */

export const template = `// Generated by the Pomegranate cli on {{creationDate}}

import {CreatePlugin} from 'pomegranate'

export const Plugin = CreatePlugin('command')
  .configuration({
    name: '{{name}}',
  })
  .variables({})
  .directories([])
  .commands(() => {
    
  })
  .installs([])
`