/**
 * @file TsInjectablePlugin
 * @author Jim Bulkowski <jim.b@paperelectron.com>
 * @project @framework
 * @license MIT {@link http://opensource.org/licenses/MIT}
 */

export const template = `// Generated by the Pomegranate cli on {{creationDate}}

import {CreatePlugin} from 'pomegranate'

export const Plugin = CreatePlugin('loghandler')
  .configuration({
    name: '{{name}}',
    depends: [],
    provides: [],
    optional: []
  })
  .variables({})
  .hooks({
    load: () => {
      return ({severity, verbocity, messages}, {source, logLevel, logFormat}) => {
        // console[severity](source, ...messages)
      }
    },
    start: () => {
      
    },
    stop: () => {
      
    }
  })
  .directories([])
  .commands(() => {
    
  })
  .installs([])
`